displayName: Path Auth Redirector Plugin
type: middleware
iconPath: .assets/icon.png

import: github.com/WithourAI/path-auth-redirector

summary: "A simple plugin to extract and assign authorisation header from request path"

testData:
  regex: "/sk/(?P<token>[^/]+)(.*)"
  replacement: "$2"
  headerName: "Authorization"
  headerPrefix: "Bearer "
