displayName: Path auth redirector middleware
type: middleware
iconPath: .assets/icon.png

import: github.com/WithourAI/path-auth-redirector

summary: 'A simple plugin to extract and assign authorisation header from request path '
